# Encrypted key doc
#   https://docs.travis-ci.com/user/encryption-keys
#
# Encrypted key commands
#   gem install travis
#   travis pubkey
#   travis encrypt DOCKER_PASSWORD=*********** --add
sudo: required
services:
- docker
env:
  global:
  - DOCKER_USERNAME=guillaumejacquenot
  - secure: "qaNGWHQn2lkTRh2PymqSk8jW7GPXsMw7rtC5EmVswqcgqywEoORGSodxkfarIQjzp48QpoQOk6knkiLvMzLn0TgSqpV3uohPLXR90Pf3E5wjh/GQm5LaO5rle0qBPlNcE8CVWaCEzvcVtmm01mw0LQRCKIZKxNWNQF+enwZNEglfpoeTDugTi7LAFkMio+GB3qm4iYtK1e7jytjoVhDqUc9sQRxy5m3i1JpXfVLW4B5HqnP6loYLdlUzx+SYtK8wWb9R0gNtq1QufVo1cMZqmcLE2YOKT8RY4PuYHAJB3hW75Ur72HlqnJLh9gZ1OTKkFwEsApmK/0nTgVgMO5JzArvbnRNUC9lzOMRzwgF7iZXDZuvIFZ96yFO8seayxPXVZcz7ilq0VkP48+LODDjhrdDseqVeKkKrcipftnQsCjdP4SmgsMpLDDxF2Zz9w+MejgDNZi7OZEN+03lRkSoS8oCYHjCYC6EznFw9lpxk6ULrDWJAd0hFcSCcyXLdOx9JZNs5tp65bRsA4yju0kIzHhUu73OaG5epJ+L/s0BnOMLKXEmtaTlKQ6P+fSACq/Q8KNYBTl0lphYg7j4xbBxYKqwq4kynWCx0HEWaa/Z6MiGIMj6W/YMGRElaf6sRJe1xIcK+IayAAYPAC8mQnCaUGW2QEPpRL3EFpefo/ZaXteQ="

before_install:
- echo "Before install"

before_script:
- docker pull sirehna/base-image-debian8-gcc492 || true

script:
- docker build --pull --cache-from sirehna/base-image-debian8-gcc492 --tag sirehna/base-image-debian8-gcc492 .

after_script:
- docker images

after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]];
  then
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
  docker push sirehna/base-image-debian8-gcc492 ;
  fi

notifications:
  email: true
